export enum ReqestTypeEnum{
 CREATE_RESOURCE_REQUEST = 'CREATE_RESOURCE_REQUEST',
 CREATE_FILE_RESOURCE_REQUEST = 'CREATE_FILE_RESOURCE_REQUEST',
 UPDATE_RESOURCE_REQUEST = 'UPDATE_RESOURCE_REQUEST',
 GET_RESOURCE_REQUEST = 'GET_RESOURCE_REQUEST',
 DELETE_RESOURCE_REQUEST = 'DELETE_RESOURCE_REQUEST',
}